[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
robinhood_testnet = "https://rpc.testnet.chain.robinhood.com"

[etherscan]
robinhood_testnet = { key = "placeholder", url = "https://explorer.testnet.chain.robinhood.com/api/" }
